name: "Hello Actions"
description: "Greet someone"
author: "I-Cat@github.com"

inputs:
  MY_NAME: "@I-Cat"
    description: "Who to greet"
    required: true
    default: "World"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
